services:
  - type: web
    name: attendance-marking-backend
    env: python
    pythonVersion: 3.11.8
    region: oregon  # or choose your preferred region
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    autoDeploy: true
